node ./scraper/scraper.js http://www.theguardian.com/crosswords/quiptic/93 ./crosswords
node ./scraper/scraper.js http://www.theguardian.com/crosswords/quiptic/92 ./crosswords
node ./scraper/scraper.js http://www.theguardian.com/crosswords/quiptic/91 ./crosswords
node ./scraper/scraper.js http://www.theguardian.com/crosswords/quiptic/90 ./crosswords
node ./scraper/scraper.js http://www.theguardian.com/crosswords/quiptic/89 ./crosswords
node ./scraper/scraper.js http://www.theguardian.com/crosswords/quiptic/88 ./crosswords
node ./scraper/scraper.js http://www.theguardian.com/crosswords/quiptic/87 ./crosswords
node ./scraper/scraper.js http://www.theguardian.com/crosswords/quiptic/86 ./crosswords
node ./scraper/scraper.js http://www.theguardian.com/crosswords/quiptic/85 ./crosswords