branch-defaults:
  master:
    environment: onedown-dev-env
global:
  application_name: One Down
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2014.09 v1.2.0 running Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
